[workspace]
members = ["persist"]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.75"
aws-sdk-dynamodb = "1.9.0"
persist.path = "persist"

[workspace.package]
edition = "2021"
version = "0.0.0"
