services:
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
    ports:
     - 8001:8001
  localstack:
    image: localstack/localstack:latest
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: dynamodb
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
